"""Render a parsed deck into a browsable reference HTML page.

The page inlines the same theme CSS used by the Anki cards (scoped under
``.anki-gen-page``), so the two outputs share one styling source. Field content
is treated as HTML — exactly as Anki renders note fields — so authored markup
and entities pass through unchanged.
"""

from __future__ import annotations

import re
from pathlib import Path

from jinja2 import Environment

from .schema import Deck, Section
from .theme import load_theme_css

# Reveal a cloze deletion {{cN::answer}} or {{cN::answer::hint}} as highlighted text.
_CLOZE = re.compile(r"\{\{c\d+::(.*?)(?:::.*?)?\}\}", re.DOTALL)

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ deck.name }}</title>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:wght@300;400;500&display=swap" rel="stylesheet">
<style>
{{ css }}
</style>
</head>
<body class="anki-gen-page">
<div class="page-wrapper">
  <header>
    <h1>{{ deck.name }}</h1>
{% if deck.description %}
    <p class="deck-description">{{ deck.description }}</p> <p class="deck-description" style="font-size: 10px">(Cloze cards are one concept with the 'missing concept' hidden not a Q&A, here it is in color and no answer.)</p>
{% endif %}
    <div class="deck-meta">{{ note_count }} notes · {{ deck.sections|length }} sections · generated by anki-gen</div>
  </header>
{% for section in sections %}
  <div class="section">
    <div class="section-header">
      <span class="section-title">{{ section.title }}</span>
      <span class="section-count">{{ section.rows|length }} cards</span>
    </div>
    <table>
      <thead>
        <tr><th class="col-q">Prompt</th><th>Answer</th></tr>
      </thead>
      <tbody>
{% for row in section.rows %}
        <tr>
          <td class="col-q">{% if row.term %}<span class="term">{{ row.term }}</span> {% endif %}{{ row.q }}</td>
          <td>{{ row.a }}</td>
        </tr>
{% endfor %}
      </tbody>
    </table>
  </div>
{% endfor %}
  <footer>Generated by anki-gen — author once, build Anki deck + this page from one source.</footer>
</div>
</body>
</html>
"""


def reveal_cloze(text: str) -> str:
    """Replace cloze deletions with their highlighted answers for the page."""
    return _CLOZE.sub(r'<span class="cloze">\1</span>', text)


def _section_rows(section: Section) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for card in section.cards:
        if card.note_type == "cloze":
            rows.append(
                {"term": card.term, "q": reveal_cloze(card.fields.get("text", "")), "a": ""}
            )
        else:
            rows.append(
                {
                    "term": card.term,
                    "q": card.fields.get("front", ""),
                    "a": card.fields.get("back", ""),
                }
            )
    return rows


def render_page(deck: Deck) -> str:
    """Return the reference HTML page for ``deck`` as a string."""
    css = load_theme_css(deck.theme)
    env = Environment(autoescape=False, trim_blocks=True, lstrip_blocks=True)
    template = env.from_string(_TEMPLATE)

    sections = [
        {"title": s.title, "rows": _section_rows(s)} for s in deck.sections
    ]
    note_count = sum(len(s["rows"]) for s in sections)

    return template.render(
        deck=deck, css=css, sections=sections, note_count=note_count
    )


def write_page(deck: Deck, out_path: str | Path) -> None:
    """Render ``deck`` and write the reference page to ``out_path``."""
    Path(out_path).write_text(render_page(deck), encoding="utf-8")
