"""Render a parsed deck into a browsable reference HTML page.

The page inlines the same theme CSS used by the Anki cards (scoped under
``.anki-gen-page``), so the two outputs share one styling source. Field content
is treated as HTML — exactly as Anki renders note fields — so authored markup
and entities pass through unchanged.
"""

from __future__ import annotations

import re
from html import escape
from pathlib import Path
from typing import Mapping, Optional

from jinja2 import Environment

from .mathjax import deck_has_math, mathjax_head_html
from .media import ResolvedMedia, data_uri
from .schema import Card, Deck, Section
from .theme import load_theme_css

MediaMap = Mapping[str, ResolvedMedia]

# Reveal a cloze deletion {{cN::answer}} or {{cN::answer::hint}} as highlighted text.
_CLOZE = re.compile(r"\{\{c\d+::(.*?)(?:::.*?)?\}\}", re.DOTALL)

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ deck.name }}</title>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:wght@300;400;500&display=swap" rel="stylesheet">
<style>
{{ css }}
</style>
{% if mathjax %}
{{ mathjax }}
{% endif %}
</head>
<body class="anki-gen-page">
<div class="page-wrapper">
  <header>
    <h1>{{ deck.name }}</h1>
{% if deck.description %}
    <p class="deck-description">{{ deck.description }}</p> <p class="deck-description" style="font-size: 10px">(Cloze cards are one concept with the 'missing concept' hidden not a Q&A, here it is in color and no answer.)</p>
{% endif %}
    <div class="deck-meta">{{ note_count }} notes · {{ deck.sections|length }} sections · generated by anki-gen</div>
  </header>
{% for section in sections %}
  <div class="section">
    <div class="section-header">
      <span class="section-title">{{ section.title }}</span>
      <span class="section-count">{{ section.rows|length }} cards</span>
    </div>
    <table>
      <thead>
        <tr><th class="col-q">Prompt</th><th>Answer</th></tr>
      </thead>
      <tbody>
{% for row in section.rows %}
        <tr>
          <td class="col-q">{% if row.term %}<span class="term">{{ row.term }}</span> {% endif %}{{ row.image_front }}{{ row.q }}</td>
          <td>{{ row.image_back }}{{ row.a }}</td>
        </tr>
{% endfor %}
      </tbody>
    </table>
  </div>
{% endfor %}
  <footer>Generated by anki-gen — author once, build Anki deck + this page from one source.</footer>
</div>
</body>
</html>
"""


def reveal_cloze(text: str) -> str:
    """Replace cloze deletions with their highlighted answers for the page."""
    return _CLOZE.sub(r'<span class="cloze">\1</span>', text)


def _image_figure(card: Card, media: Optional[MediaMap]) -> str:
    """Inline a card's image as a self-contained base64 ``<figure>``, or ``""``.

    Uses a ``data:`` URI (not a filename) so the page stays a single file, mirroring
    how the deck cards show the same image.
    """
    if not card.image or not media:
        return ""
    resolved = media.get(card.image)
    if resolved is None:
        return ""
    alt = escape(card.term or card.image_credit, quote=True)
    html = f'<figure class="media"><img src="{data_uri(resolved)}" alt="{alt}">'
    if card.image_credit:
        html += f"<figcaption>{escape(card.image_credit)}</figcaption>"
    return html + "</figure>"


def _section_rows(section: Section, media: Optional[MediaMap]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for card in section.cards:
        image = _image_figure(card, media)
        # Mirror the card: a question-side image sits in the prompt column, an
        # answer-side ("hidden until the answer") image in the answer column.
        image_front = image if card.image_side in ("both", "front") else ""
        image_back = image if card.image_side in ("both", "back") else ""
        if card.note_type == "cloze":
            q = reveal_cloze(card.fields.get("text", ""))
            a = ""
        else:
            q = card.fields.get("front", "")
            a = card.fields.get("back", "")
        rows.append(
            {"term": card.term, "q": q, "a": a,
             "image_front": image_front, "image_back": image_back}
        )
    return rows


def render_page(deck: Deck, media: Optional[MediaMap] = None) -> str:
    """Return the reference HTML page for ``deck`` as a string.

    ``media`` maps image references to staged files; images are inlined as base64
    ``data:`` URIs so the page is a single self-contained file. When omitted, cards
    render without images.
    """
    css = load_theme_css(deck.theme)
    env = Environment(autoescape=False, trim_blocks=True, lstrip_blocks=True)
    template = env.from_string(_TEMPLATE)

    sections = [
        {"title": s.title, "rows": _section_rows(s, media)} for s in deck.sections
    ]
    note_count = sum(len(s["rows"]) for s in sections)

    # Inline MathJax only when the deck contains LaTeX, so math-free pages stay
    # lean. The deck's authored fields render identically to the Anki cards.
    mathjax = mathjax_head_html() if deck_has_math(deck) else ""

    return template.render(
        deck=deck, css=css, sections=sections, note_count=note_count, mathjax=mathjax
    )


def write_page(deck: Deck, out_path: str | Path, media: Optional[MediaMap] = None) -> None:
    """Render ``deck`` and write the reference page to ``out_path``."""
    Path(out_path).write_text(render_page(deck, media), encoding="utf-8")
